export const WISATA = {
  LOAD: "WISATA_LOAD",
  LOAD_SUCCESS: "WISATA_LOAD_SUCCESS",
  LOAD_ERROR: "WISATA_LOAD_ERROR",
  SET_CURRENT: "SET_CURRENT",
  SET_CURRENT_SUCCESS: "SET_CURRENT_SUCCESS",
  SET_CURRENT_ERROR: "SET_CURRENT_ERROR",
};
